name: Ansible Lint
description: Run Ansible Lint
inputs:
  path:
    required: false
    default: "."
runs:
  using: docker
  image: 'Dockerfile'
  entrypoint: /usr/local/bin/ansible-lint
  env:
    GITHUB_ACTIONS: "true"
    GITHUB_WORKFLOW: "{{ github.workflow.name }}"
  args:
    - -c /config/.ansible-lint
    - ${{ inputs.path }}
